plugins {
    id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
    id "java-library"
    id "com.diffplug.spotless" version "${spotless_version}"
    id "idea"
}

version = mod_version
group = maven_group

base {
    archivesName = "_custom_${archives_base_name}-${minecraft_version}-fabric"
}

loom {
    if (file("src/main/resources/${archives_base_name}.accesswidener").exists()) {
        accessWidenerPath = file("src/main/resources/${archives_base_name}.accesswidener")
    } else if (file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
    }
    runs {
        client {
            getProgramArguments().add("--username")
            getProgramArguments().add("DevPlayer")
            getProgramArguments().add("--uuid")
            getProgramArguments().add("00000000-0000-0000-0000-000000000000")
            getJvmArguments().addAll(Arrays.asList("-Dfabric.disableYggdrasil=true"))
            getJvmArguments().addAll(Arrays.asList("-Dfabric.disableRealms=true"))
            getGenerateRunConfig().set(true)
        }
    }
}

fabricApi {
    configureDataGeneration {
        outputDirectory = file("src/generated/resources")
        createRunConfiguration = true
        modId = mod_id
        strictValidation = true
        addToResources = true
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "org.jetbrains:annotations:latest.release"
    compileOnly "com.github.spotbugs:spotbugs-annotations:latest.release"
}

// Common Repositories
repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com"
    }
    maven {
        name = "Cassian"
        url = "https://maven.cassian.cc"
        content {
            includeGroupAndSubgroups("cc.cassian")
        }
    }
}

// Mod Menu
dependencies {
    localRuntime( "com.terraformersmc:modmenu:${modmenu_version}" )
}

// Just Enough Items
if (recipe_viewer == "jei") {
    dependencies {
        localRuntime( "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}" )
    }
}

// Reliable Recipe Viewer
if (recipe_viewer == "rrv") {
    dependencies {
        localRuntime( "cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}" )
    }
}

// Mixin Extras
if (file("src/main/resources/${archives_base_name}.mixins.json").exists()) {
    dependencies {
        implementation( annotationProcessor( "io.github.llamalad7:mixinextras-common:${mixinextras_version}" ))
    }
    dependencies {
        implementation( annotationProcessor( "io.github.llamalad7:mixinextras-fabric:${mixinextras_version}" ))
    }
}

// Build Dependencies
if (file("build-dependencies.gradle").exists()) {
    apply from: "build-dependencies.gradle"
}

// Runtime Dependencies
if (file("build-runtime.gradle").exists()) {
    apply from: "build-runtime.gradle"
}

// Spotless Config
if (file("build-spotless.gradle").exists()) {
    apply from: "build-spotless.gradle"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
        excludeDirs += file('run')
        excludeDirs += file('runs')
        excludeDirs += file('src/generated/resources/.cache')
        excludeDirs += file('gradlew')
        excludeDirs += file('gradlew.bat')
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(25)
    it.options.encoding = "UTF-8"
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('tag', 'reason:a:Reason for Override:')
    options.addStringOption('tag', 'desc:a:Description:')
    options.addStringOption('tag', 'spec:a:Specification:')
}

def mod_name_final = mod_name_custom.toBoolean() ? "${mod_name} [C]" : mod_name

processResources {
    def stringProperties = new LinkedHashMap(providers.gradlePropertiesPrefixedBy('').get())
    stringProperties.put("mod_name_final", mod_name_final)
    stringProperties.each { key, value -> inputs.property(key as String, value) }
    filesMatching(['fabric.mod.json', 'en_us.json']) {
        filter { line -> line.contains('"$schema":') ? null : line }
        filter { line -> line.startsWith('/*') ? null : line }
        filter { line -> line.startsWith('//') ? null : line }
        filter { line -> line.trim().isEmpty() ? null : line }
        expand(stringProperties) { escapeBackslash = true }
    }
}

jar {
    manifest {
        attributes(
            [
                "Specification-Title"     : mod_id,
                "Specification-Vendor"    : mod_authors,
                "Specification-Version"   : "1",
                "Implementation-Title"    : mod_name_final,
                "Implementation-Version"  : mod_version,
                "Implementation-Vendor"   : mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            ]
        )
    }
}
