// Modrinth Maven
repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

// Mixin Constraints
dependencies {
    include(implementation("com.moulberry:mixinconstraints:${mixin_constraints_version}"))
}

// JEI
dependencies {
    compileOnly( "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}" )
    compileOnly( "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}" )
}

// RRV
dependencies {
    compileOnly( "cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}" )
}

// Create
dependencies {
    implementation(localRuntime("maven.modrinth:dKvj0eNn:${create_version}"))
}

// Farmer's Delight
dependencies {
    implementation(localRuntime("maven.modrinth:7vxePowz:${farmersdelight_version}"))
}
