// Mixin Constraints - https://github.com/moulberry/mixinconstraints
def mixinConstraintsVersion= "1.1.0"
dependencies {
    include(implementation("com.moulberry:mixinconstraints:${mixinConstraintsVersion}"))
}

// JEI
dependencies {
    compileOnly( "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}" )
    compileOnly( "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}" )
}

// RRV
dependencies {
    compileOnly( "cc.cassian.rrv:reliable-recipe-viewer-fabric:${rrv_version}" )
}
