// Audaki Cart Engine
dependencies {
    runtimeOnly("maven.modrinth:V8qsCwta:${audaki_cart_engine_version}")
}

// Create
dependencies {
    runtimeOnly("maven.modrinth:dKvj0eNn:${create_version}")
}

// Diagonal Fences
dependencies {
    runtimeOnly("maven.modrinth:QAGBst4M:${puzzles_version}")
    runtimeOnly("maven.modrinth:ohNO6lps:${forge_config_version}")
    runtimeOnly("maven.modrinth:IKARgflD:${diagonal_fences_version}")
}

// Diagonal Walls
dependencies {
    runtimeOnly("maven.modrinth:QAGBst4M:${puzzles_version}")
    runtimeOnly("maven.modrinth:ohNO6lps:${forge_config_version}")
    runtimeOnly("maven.modrinth:FQgc8dib:${diagonal_walls_version}")
}

// KleeSlabs
dependencies {
    runtimeOnly("maven.modrinth:MBAkmtvl:${balm_version}")
    runtimeOnly("maven.modrinth:7uh75ruZ:${kleeslabs_version}")
}

// Rail Placement Fix
dependencies {
    runtimeOnly("maven.modrinth:7z0IZqoa:${rail_placement_fix_version}")
}
