# project properties
project_name=

# mod properties
mod_name=
mod_id=
mod_version=
mod_authors=STL
mod_license=All Rights Reserved
mod_description=

# custom tag
mod_name_custom=true

# mod links
url_homepage=https://github.com/stlouisn/
git_sources=https://github.com/stlouisn/
git_upstream=

# recipe viewer (jei or rrv)
recipe_viewer=rrv

# maven
archives_base_name=
maven_group=

# gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.warning.mode=all
org.gradle.debug=false
org.gradle.configuration-cache=false
