# project properties
project_name=Fabric Template

# mod properties
mod_name=mod_name
mod_id=mod_id
mod_version=mod_version
mod_authors=mod_author
mod_license=mod_license
mod_description=mod_description

# custom tag
mod_name_custom=false

# mod links
url_homepage=https://github.com/stlouisn/
git_sources=https://github.com/stlouisn/
git_upstream=

# recipe viewer (jei or rrv)
recipe_viewer=rrv

# maven
archives_base_name=archive_name
maven_group=com.mod_id

# gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.warning.mode=all
org.gradle.debug=false
org.gradle.configuration-cache=false

# fabric https://fabricmc.net/develop
minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.155.2+26.2

# minecraft
minecraft_min_version=26.2

# mixinextras https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.4

# spotless https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-plugin-gradle/versions
spotless_version=8.8.0

# modmenu https://modrinth.com/mod/modmenu/versions?l=fabric&g=26.2
modmenu_version=20.0.1

# jei https://maven.blamejared.com/mezz/jei/jei-26.2-fabric/maven-metadata.xml
jei_version=30.14.0.89

# rrv https://maven.cassian.cc/cc/cassian/rrv/reliable-recipe-viewer-fabric/?C=N;O=D
rrv_version = 8.6.4+26.2
