# suppress inspection "SpellCheckingInspection" for whole file

# ------------------------------------------------------------------------------------------

# fabric https://fabricmc.net/develop
minecraft_version=26.2
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT
fabric_api_version=0.159.0+26.2

# minecraft
minecraft_min_version=26.2

# mixinextras https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.5

# spotless https://mvnrepository.com/artifact/com.diffplug.spotless/spotless-plugin-gradle/versions
spotless_version=8.10.2

# modmenu https://modrinth.com/mod/modmenu/versions?l=fabric&g=26.2
modmenu_version=20.0.1

# ------------------------------------------------------------------------------------------

# jei https://maven.blamejared.com/mezz/jei/jei-26.2-fabric/maven-metadata.xml
jei_version=30.32.0.209

# rrv https://maven.cassian.cc/cc/cassian/rrv/reliable-recipe-viewer-fabric/maven-metadata-local.xml
rrv_version = 8.10.4+26.2

# ------------------------------------------------------------------------------------------

# mixin constraints - https://mvnrepository.com/artifact/com.moulberry/mixinconstraints/versions
mixin_constraints_version=1.1.0

# ------------------------------------------------------------------------------------------

# balm - https://modrinth.com/mod/balm/versions?g=26.2&l=fabric
balm_version=tYnUhVmF

# kleeslabs - https://modrinth.com/mod/kleeslabs/versions?g=26.2&l=fabric
kleeslabs_version=5UjTYBjC

# create - https://modrinth.com/mod/create-fly/versions?g=26.2&l=fabric
create_version=phlsMPgT

# farmer's delight - https://modrinth.com/mod/farmers-delight-refabricated/versions?g=26.2&l=fabric
farmersdelight_version=jUfTpAIM

# puzzles - https://modrinth.com/mod/puzzles-lib/versions?g=26.2&l=fabric
puzzles_version=KU5rZUAR

# forge config - https://modrinth.com/mod/forge-config-api-port/versions?g=26.2&l=fabric
forge_config_version=rSd3GiG8

# diagonal fences - https://modrinth.com/mod/diagonal-fences/versions?g=26.2&l=fabric
diagonal_fences_version=XxnvsgPA

# diagonal walls - https://modrinth.com/mod/diagonal-walls/versions?g=26.2&l=fabric
diagonal_walls_version=CPViyp2m

# audaki cart engine - https://modrinth.com/mod/audaki-cart-engine/versions?g=26.2&l=fabric
audaki_cart_engine_version=xnXxitQi

# rail placement fix - https://modrinth.com/mod/rail-placement-fix/versions?g=26.2&l=fabric
rail_placement_fix_version=qbowj3cu
